/* tslint:disable */
/* eslint-disable */
/**
 * Uniclass API
 * <p>Uniclass API - Student, Teacher & Operation</p>  <h5>To use with Generator, First install ...</h5> <pre>     yarn add -D @openapitools/openapi-generator-cli </pre> <h5>Then run ...</h5> <pre>     npx @openapitools/openapi-generator-cli generate --skip-validate-spec -i https://uniclass-api---dev-2fce6.ondigitalocean.app/swagger-yaml -g typescript-axios --additional-properties=paramNaming=snake_case,prependFormOrBodyParameters,sortModelPropertiesByRequiredFlag,useSingleRequestParameter -o ./apps/uniclass-api-consumer/src/api/ </pre> <h5>NOTE: replace <b>-o</b> with <b>api</b> directory</h5> 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

